# Generated by Django 5.2.4 on 2025-08-03 16:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name='Дата "ленивого" удаления',
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("sum", "Сумма двух чисел"),
                            ("countdown", "Обратный отсчёт"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Запланировано"),
                            ("in_progress", "Выполняется"),
                            ("completed", "Выполнено"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
