[tool.black]
line-length = 120
target-version = ["py313"]

[tool.flake8]
inline-quotes = "double"
ignore = "E203, W503, S106, S101"
max-line-length = 120
extend-select = "G"

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
force_single_line = true
line_length = 120
use_parentheses = true
py_version=313

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[bandit]
exclude = "tests"
skips = "B101, B601"
